apiVersion: kai.io/v1alpha1
kind: FineTuneTask
metadata:
  name: llamafactory-finetune
  namespace: default
spec:
  llamafactory:
    modelPath: /models/llama-7b
    stage: sft
    trainData: /data/train.jsonl
    finetuningType: lora
    loraRank: 8
    loraAlpha: 16
    batchSize: 4
    learningRate: "0.0001"
    numEpochs: 3
