apiVersion: kai.io/v1alpha1
kind: FineTuneTask
metadata:
  name: lora-finetune
  namespace: default
spec:
  lora:
    modelPath: /models/llama-7b
    trainData: /data/train.jsonl
    outputDir: /models/output
    loraRank: 8
    loraAlpha: 16
    batchSize: 4
    learningRate: "0.0001"
    epochs: 3
