# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/kai.io_devtasks.yaml
- bases/kai.io_traintasks.yaml
- bases/kai.io_finetunetasks.yaml
- bases/kai.io_evaltasks.yaml
- bases/kai.io_inferencetasks.yaml
# +kubebuilder:scaffold:crdkustomizeresource
